name: PR Automation

on:
  pull_request:
    types: [opened, reopened]

jobs:
  pr-automation:
    name: PR Automation
    runs-on: ubuntu-latest

    steps:
      - name: Add labels based on files changed
        uses: actions/labeler@v5
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/labeler.yml

      - name: Auto-assign reviewers
        uses: kentaro-m/auto-assign-action@v1.2.6
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/auto-assign.yml

      - name: Add size label
        uses: pascalgn/size-label-action@v0.5.4
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          sizes: >
            {
              "0": "XS",
              "20": "S",
              "50": "M",
              "200": "L",
              "800": "XL",
              "2000": "XXL"
            }

      - name: Check if PR is from fork
        id: check-fork
        run: |
          if [ "${{ github.event.pull_request.head.repo.full_name }}" != "${{ github.repository }}" ]; then
            echo "is_fork=true" >> $GITHUB_OUTPUT
          else
            echo "is_fork=false" >> $GITHUB_OUTPUT
          fi

      - name: Add fork label
        if: steps.check-fork.outputs.is_fork == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['external-contribution']
            })

      - name: Welcome first-time contributors
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: |
            👋 Thanks for opening your first pull request!

            Please make sure you have:
            - [ ] Read our [contributing guidelines](./CODE_OF_CONDUCT.md)
            - [ ] Tested your changes locally
            - [ ] Added appropriate documentation if needed

            A maintainer will review your PR soon. Thanks for contributing to OCM Dashboard! 🚀
