name: Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

env:
  REGISTRY: quay.io
  IMAGE_NAME: open-cluster-management/ocm-dashboard
  HELM_REPO_URL: https://open-cluster-management.io/helm-charts
  # Define supported platforms for release builds
  PLATFORMS: linux/amd64,linux/arm64,linux/ppc64le,linux/s390x

jobs:
  release-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ env.PLATFORMS }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Install cosign
        uses: sigstore/cosign-installer@v3
        with:
          cosign-release: "v2.1.1"

      - name: Sign the published Docker image
        env:
          TAGS: ${{ steps.meta.outputs.tags }}
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}

  release-helm-chart:
    runs-on: ubuntu-latest
    needs: release-image
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Update Chart version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          sed -i "s/^version:.*/version: $VERSION/" charts/ocm-dashboard/Chart.yaml
          sed -i "s/^appVersion:.*/appVersion: \"$VERSION\"/" charts/ocm-dashboard/Chart.yaml

      - name: Package Helm chart
        run: |
          helm package charts/ocm-dashboard

      - name: Clone helm-charts repository
        uses: actions/checkout@v4
        with:
          repository: open-cluster-management-io/helm-charts
          path: helm-charts
          token: ${{ secrets.OCM_BOT_PAT }}

      - name: Update helm-charts repository
        run: |
          cp ocm-dashboard-*.tgz helm-charts/
          cd helm-charts
          helm repo index . --url ${{ env.HELM_REPO_URL }}
          git add .
          git commit -m "Add ocm-dashboard chart ${GITHUB_REF#refs/tags/}"
          git push

  create-release:
    runs-on: ubuntu-latest
    needs: [release-image, release-helm-chart]
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ## OCM Dashboard ${{ github.ref }}

            ### Docker Image
            ```bash
            docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${GITHUB_REF#refs/tags/}
            ```

            ### Helm Chart
            ```bash
            helm repo add ocm https://open-cluster-management.io/helm-charts
            helm repo update
            helm install ocm-dashboard ocm/ocm-dashboard --version ${GITHUB_REF#refs/tags/v}
            ```

            ### What's Changed
            See [CHANGELOG.md](https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md) for details.
          draft: false
          prerelease: false
